version: "3.7"

services: 
  db:
      image: postgres:13.2
      hostname: postgres
      container_name: postgres
      ports:
        - "5439:5432"
      environment: # should be consistent with config.yml file 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: the_tally_dev
        PGDATA: /data/db
      volumes:
        - ./compose/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - theTallydbVolume:/data/db

volumes:
  theTallydbVolume:
    driver: local